# http://docs.travis-ci.com/user/languages/go/#Default-Test-Script
language: go
sudo: false
go: # https://github.com/atotto/travisci-golang-example
- "1.4"
- "1.5"
- stable
- master
env:
  matrix:
    - GOOS=linux
    - GOOS=darwin
    - GOOS=freebsd
    - GOOS=windows
matrix:
  allow_failures:
  - go: "1.3"
  - go: "1.4"
branches:
  only: [master, develop]
before_install:
- mkdir -p "${GOPATH}/src/purl.mro.name/recorder"
- cd "${GOPATH}/src/purl.mro.name/recorder" && ln -s "${TRAVIS_BUILD_DIR}/src" radio
- ls -l "${GOPATH}/src/purl.mro.name/recorder"
install:
- go get
  github.com/stretchr/testify
  github.com/yhat/scrape
  github.com/bogem/id3v2
- cp "${GOPATH}/src/github.com/bogem/id3v2/testdata/test.mp3" "${TRAVIS_BUILD_DIR}/src/enclosure-tag-cmd/testdata/file.mp3"
- cp "${GOPATH}/src/github.com/bogem/id3v2/testdata/back_cover.jpg" "${TRAVIS_BUILD_DIR}/src/enclosure-tag-cmd/testdata/image.jpg"
script:
- go vet && go test -v
  purl.mro.name/recorder/radio/scrape
  purl.mro.name/recorder/radio/scrape/br
  purl.mro.name/recorder/radio/scrape/b3
  purl.mro.name/recorder/radio/scrape/b4
  purl.mro.name/recorder/radio/scrape/dlf
  purl.mro.name/recorder/radio/scrape/m945
  purl.mro.name/recorder/radio/scrape/radiofabrik
  purl.mro.name/recorder/radio/scrape/wdr
  purl.mro.name/recorder/radio/scrape-cmd
  purl.mro.name/recorder/radio/enclosure-tag-cmd
