# http://docs.travis-ci.com/user/languages/go/#Default-Test-Script
language: go
sudo: false
go: # https://github.com/atotto/travisci-golang-example
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - 1.6
 - release
 - tip
before_install:
 - mkdir -p "$GOPATH/src/purl.mro.name/recorder"
 - cd "$GOPATH/src/purl.mro.name/recorder" && ln -s "$TRAVIS_BUILD_DIR/src" radio
 - ls -l "$GOPATH/src/purl.mro.name/recorder"
install:
 - go get github.com/stretchr/testify
 - go get github.com/yhat/scrape
script:
 - go test -v purl.mro.name/recorder/radio/scrape
 - go test -v purl.mro.name/recorder/radio/scrape/br
 - go test -v purl.mro.name/recorder/radio/scrape/dlf
 - go test -v purl.mro.name/recorder/radio/scrape/m945
 - go test -v purl.mro.name/recorder/radio/cmd
